global:
  iotdb_zip_dir: "/root/packages/20240401-timechodb-1321-rc1-da56ef1b8c.zip"
  iotdb_dir_name: "iotdb"
  iotdb_lib_dir: /data/iotdb/iotdb-enterprise-1.3.1.1-bin/lib
  user: "root"
  password: "Dwf12345"
  ssh_port: 22
  cn_seed_config_node: 172.20.31.16:10710
  dn_seed_config_node: 172.20.31.16:10710
  iotdb_admin_user: root
  iotdb_admin_password: root

  datanode-env.sh:
    MEMORY_SIZE: 12G
  confignode-env.sh:
    MEMORY_SIZE: 2G

  iotdb-confignode.properties:
    cn_internal_port: 10710
    cn_metric_reporter_list: PROMETHEUS
    cn_metric_level: IMPORTANT
    cn_metric_prometheus_reporter_port: 9091
  iotdb-datanode.properties:
    dn_rpc_port: 6667
    dn_internal_port: 10730
    dn_metric_reporter_list: PROMETHEUS
    dn_metric_level: IMPORTANT
    dn_metric_prometheus_reporter_port: 9092

  iotdb-common.properties:
    cluster_name: v1321-rc1
    config_node_consensus_protocol_class: "org.apache.iotdb.consensus.ratis.RatisConsensus"
    schema_replication_factor: 3
    schema_region_consensus_protocol_class: "org.apache.iotdb.consensus.ratis.RatisConsensus"
    data_replication_factor: 3
    data_region_consensus_protocol_class: "org.apache.iotdb.consensus.iot.IoTConsensus"
    enable_seq_space_compaction: "false"
    enable_unseq_space_compaction: "false"
    enable_cross_space_compaction: "false"

confignode_servers:
  - name: confignode_1
    deploy_dir: "/root/data/rn1321-rc1/opskit-upgrade/deploy/a"
    iotdb-confignode.properties:
      cn_internal_address: 172.20.31.16
  - name: confignode_2
    deploy_dir: "/root/data/rn1321-rc1/opskit-upgrade/deploy/a"
    iotdb-confignode.properties:
      cn_internal_address: 172.20.31.17
  - name: confignode_3
    deploy_dir: "/root/data/rn1321-rc1/opskit-upgrade/deploy/a"
    iotdb-confignode.properties:
      cn_internal_address: 172.20.31.18

datanode_servers:
  - name: datanode_1
    deploy_dir: "/root/data/rn1321-rc1/opskit-upgrade/deploy/a"
    iotdb-datanode.properties:
      dn_rpc_address: 172.20.31.16
      dn_internal_address: 172.20.31.16
  - name: datanode_2
    deploy_dir: "/root/data/rn1321-rc1/opskit-upgrade/deploy/a"
    iotdb-datanode.properties:
      dn_rpc_address: 172.20.31.17
      dn_internal_address: 172.20.31.17
  - name: datanode_3
    deploy_dir: "/root/data/rn1321-rc1/opskit-upgrade/deploy/a"
    iotdb-datanode.properties:
      dn_rpc_address: 172.20.31.18
      dn_internal_address: 172.20.31.18
